name: Pre-commit

on:
  push:
    branches: ['main', 'master']
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ['main', 'master']
  release:
    types: [published]

jobs:
  pre-commit:
    name: Pre-commit hooks execute
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: clowdhaus/terraform-composite-actions/pre-commit@main
        with:
          terraform-version: 1.7.0
          terraform-docs-version: v0.17.0
          tflint-version: v0.50.3
          args: "--all-files --color always --show-diff-on-failure"
