name: Terratest

on: 
  push:
    branches: ['main', 'master']
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ['main', 'master']
  release:
    types: [published]
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed
    branches:
      - main

jobs:
  terratest:
    name: Run Terratest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Install dependencies
        working-directory: tests
        run: go mod download

      - name: Run Terratest
        working-directory: tests
        run: go test -v